---
- name: Debug message.
  ansible.builtin.debug:
    msg: "This is an agent. The hostname is {{ansible_facts['hostname']}}"

- include_tasks: install-rke2-agent.yaml
- include_tasks: config-rke2-agent.yaml
- include_tasks: start-rke2-agent.yaml
